### ISSUE TITLE
Tried everything but i end up with this error

### ISSUE THREAD

**Issue by sramamkrishnan** [slmoebius/builder#1]
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 940, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 928, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/odoo-server/openerp/modules/registry.py", line 368, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/odoo-server/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/opt/odoo/odoo-server/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_model.py", line 1077, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_ui_view.py", line 264, in create
    context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 4059, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 4250, in _create
    recs._validate_fields(vals)
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/models.py", line 1267, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
_description_searchable" while parsing /opt/odoo/custom/addons/builder/views/module_view.xml:4, near
<record id="module_form" model="ir.ui.view">
            <field name="name">builder.ir.module.module.form</field>
            <field name="model">builder.ir.module.module</field>
	    <field name="arch" type="xml">
                <form string="Module">

                    <sheet>
                        <div class="oe_right oe_button_box builder_button_box" name="buttons" id="builder_button_box">

                            <ul class="nav navbar-nav navbar-right" style="">
                                                                <li class="dropdown">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                        <span class="oe_topbar_name">Backend</span>
                                        <b class="caret"/>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <button class="oe_inline oe_stat_button" string="Models" name="action_backend_models" type="object" icon="fa-code" context="{'default_module_id': id}"/>
                                        </li>
                                        <li>
                                            <button class="oe_inline oe_stat_button" string="Views" name="action_backend_views" type="object" icon="fa-columns" context="{'default_module_id': id}"/>
                                        </li>
                                        <li>
                                            <button class="oe_inline oe_stat_button" string="Actions" name="action_backend_actions" type="object" icon="fa-font" context="{'default_module_id': id}"/>
                                        </li>
                                        <li>
                                            <button class="oe_inline oe_stat_button" string="Menus" name="action_backend_menus" type="object" icon="fa-list" context="{'default_module_id': id}"/>
                                        </li>
                                        <li class="odoo_support_contact">
                                            <button class="oe_inline oe_stat_button" string="Groups" name="action_backend_groups" type="object" icon="fa-group" context="{'default_module_id': id}"/>
                                        </li>
                                        <li>
                                            <button class="oe_inline oe_stat_button" string="ACLs" name="action_backend_model_access" type="object" icon="fa-unlock" context="{'default_module_id': id}"/>
                                        </li>
                                        <li>
                                            <button class="oe_inline oe_stat_button" string="Record Rules" name="action_backend_rules" type="object" icon="fa-lock" context="{'default_module_id': id}"/>
                                        </li>
                                        <li>
                                            <button class="oe_inline oe_stat_button" string="Cron Jobs" name="action_backend_cron_jobs" type="object" icon="fa-bell-slash" context="{'default_module_id': id}"/>
                                        </li>
                                    </ul>
                                </li>
                                <li class="dropdown" invisible="1">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                        <span class="oe_topbar_name">Website</span>
                                        <b class="caret"/>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <button class="oe_inline oe_stat_button" string="Pages" name="action_website_pages" type="object" icon="fa-file" context="{'default_module_id': id}"/>
                                        </li>
                                        <li>
                                            <button class="oe_inline oe_stat_button" string="Themes" name="action_website_themes" type="object" icon="fa-html5" context="{'default_module_id': id}"/>
                                        </li>
                                        <li>
                                            <button class="oe_inline oe_stat_button" string="Snippets" name="action_website_snippets" type="object" icon="fa-puzzle-piece" context="{'default_module_id': id}"/>
                                        </li>
                                        <li>
                                            <button class="oe_inline oe_stat_button" string="Assets" name="action_website_assets" type="object" icon="fa-archive" context="{'default_module_id': id}"/>
                                        </li>
                                        <li class="odoo_support_contact">
                                            <button class="oe_inline oe_stat_button" string="Menus" name="action_website_menus" type="object" icon="fa-list" context="{'default_module_id': id}"/>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>

                        <field name="icon_image" widget="image" class="oe_avatar oe_left"/>
                        <div class="oe_title">
                            <h1>
                                <field name="shortdesc"/>
                            </h1>
                            <h3 class="oe_fade">
                                By
                                <field name="author" class="oe_inline"/>
                            </h3>
                            <div>
                                <button name="button_download" string="Download" type="object" class="oe_highlight"/>
                            </div>
                        </div>
                        <div class="oe_clear"/>
                        <notebook>
                            <page string="Information">
                                <group>
                                    <group>
                                        <field name="website" widget="url"/>
                                        <field name="category_id" widget="selection"/>
                                        <field name="summary"/>
                                    </group>
                                    <group>
                                        <field name="id" readonly="1" invisible="1"/>
                                        <field name="name"/>
                                        <field name="license"/>
                                        <field name="installed_version"/>
                                    </group>
                                </group>
                                <field name="description_html" class="oe_styling_v8"/>
                                <button string="Edit in Website" name="action_edit_description_html" type="object" class="oe_link"/>
                            </page>
                            <page string="Technical Data">
                                <group col="4">
                                    <field name="demo"/>
                                    <field name="application"/>
                                    <field name="auto_install"/>
                                </group>
                                <group string="Dependencies"/>
                                <p class="oe_grey" attrs="{'invisible': [('dependency_ids','not in',[None,False])]}">
                                    -This module does not depends on any other module.
                                </p>
                                <field name="dependency_ids">
                                    <tree string="Dependencies" context="{'default_module_id': active_id}">
                                        <field name="name"/>
                                    </tree>
                                    <form string="Dependency">
                                        <group>
                                            <group>
                                                <field name="type"/>
                                                <field name="dependency_module_id" attrs="{'invisible': [('type', 'not in', 'module')]}"/>
                                                <field name="dependency_project_id" attrs="{'invisible': [('type', 'not in', 'project')]}"/>
                                                <field name="dependency_module_name" attrs="{'invisible': [('type', 'not in', 'manual')]}"/>
                                            </group>
                                            <group>
                                                <field name="name"/>
                                            </group>
                                        </group>
                                    </form>
                                </field>
                            </page>
                            <page string="Files">
                                <div class="oe_right oe_button_box" name="buttons">
                                    <button class="oe_inline oe_stat_button" string="Import Zip" name="%(act_builder_data_import_wizard)d" type="action" icon="fa-reply" context="{}"/>
                                </div>
                                <field name="data_file_ids" nolabel="1"/>
                            </page>
                            <page string="Data" invisible="1">
                                <field name="data_ids" nolabel="1" context="{'default_module_id': active_id}"/>
                            </page>
                            <page string="Backend">
                                <notebook>
                                    <page string="Models">
                                        <div class="oe_right oe_button_box" name="buttons">
                                            <button class="oe_inline oe_stat_button" string="UML Diagram" name="action_diagram" type="object" icon="fa-magic" context="{}"/>
                                            <button class="oe_inline oe_stat_button" string="Import Models" name="%(act_builder_ir_model_import_wizard)d" type="action" icon="fa-reply" context="{}"/>
                                        </div>
                                        <field name="model_ids" editable="bottom" context="{'default_module_id': active_id}">
                                            <tree string="Models" context="{'default_module_id': active_id}">
                                                <field name="id" invisible="1"/>
                                                <field name="special_states_field_id" invisible="1"/>
                                                <field name="model"/>
                                                
                                                <field name="osv_memory"/>
                                                <field name="is_inherited"/>
                                                <field name="inherit_type"/>
                                            </tree>
                                        </field>
                                    </page>
                                    <page string="Views">
                                        <div class="oe_right oe_button_box" name="buttons">
                                            <button class="oe_inline oe_stat_button" string="Model View" name="%(act_builder_views_selector)d" type="action" icon="fa-plus" context="{'default_module_id': id}"/>
                                        </div>
                                        <field name="view_ids" nolabel="1" context="{'default_module_id': active_id}">
                                            <tree string="Views" create="1" edit="1" delete="1">
                                                <field name="model_id"/>
                                                <field name="type"/>
                                                <field name="xml_id"/>
                                                <field name="inherit_id"/>
                                                <button name="action_open_view" type="object" string="Configure" class="oe_button oe_form_button oe_link"/>
                                            </tree>
                                        </field>
                                    </page>
                                    <page string="Actions">
                                        <field name="action_window_ids" nolabel="1" context="{'default_module_id': active_id}">
                                            <tree string="Actions">
                                                <field name="name"/>
                                                <field name="model_id"/>
                                                <field name="view_mode"/>
                                                <field name="view_type"/>
                                                <field name="target"/>
                                            </tree>
                                        </field>
                                    </page>
                                    <page string="Menus">
                                        <field name="menu_ids" nolabel="1" context="{'default_module_id': active_id}">
                                            <tree string="Menus">
                                                <field name="morder" widget="handle"/>
                                                <field name="sequence"/>
                                                <field name="xml_id"/>
                                                <field name="complete_name"/>
                                            </tree>
                                        </field>
                                    </page>
                                    <page string="Groups">
                                        <field name="group_ids" nolabel="1" context="{'default_module_id': active_id}"/>
                                    </page>
                                    <page string="ACLs">
                                        <div class="oe_right oe_button_box" name="buttons">
                                            <button class="oe_inline oe_stat_button" string="Generate ACLs" name="%(act_builder_ir_model_access_generate_wizard)d" type="action" icon="fa-spinner" context="{'default_module_id': active_id}"/>
                                        </div>
                                        <field name="model_access_ids" nolabel="1" context="{'default_module_id': active_id}" mode="tree">
                                            <tree editable="bottom">
                                                <field name="name"/>
                                                <field name="model_id" domain="[('module_id', '=', active_id)]"/>
                                                <field name="group_id" domain="[('module_id', '=', active_id)]"/>
                                                <field name="perm_read"/>
                                                <field name="perm_write"/>
                                                <field name="perm_create"/>
                                                <field name="perm_unlink"/>
                                            </tree>
                                        </field>
                                    </page>
                                    <page string="Rules">
                                        <field name="rule_ids" nolabel="1" context="{'default_module_id': active_id}"/>
                                    </page>
                                    <page string="Cron Jobs">
                                        <field name="cron_job_ids" nolabel="1" context="{'default_module_id': active_id}"/>
                                    </page>

                                </notebook>
                            </page>

                            <page string="Website" invisible="1">
                                <notebook class="ui-tabs-vertical">
                                    <page string="Pages">
                                        <button string="Import Page" name="%(act_builder_website_page_import_wizard)d" type="action" class="oe_link" context="{'default_module_id': id}"/>
                                        <field name="website_page_ids" context="{'default_module_id': active_id}"/>
                                    </page>
                                    <page string="Themes">
                                        <field nolabel="1" name="website_theme_ids" context="{'default_module_id': active_id}"/>
                                    </page>
                                    <page string="Snippets">
                                        <field name="snippet_bookmarklet_url" widget="url" readonly="1" text="Create Snippet"/>
                                        <field name="website_snippet_ids"/>
                                    </page>
                                    <page string="Assets">
                                        <field nolabel="1" name="website_asset_ids" context="{'default_module_id': active_id}"/>
                                    </page>
                                    <page string="Menus">
                                        <field nolabel="1" name="website_menu_ids" context="{'default_module_id': active_id}"/>
                                    </page>
                                </notebook>
                            </page>

                        </notebook>
                    </sheet>
                </form>
            </field>
        </record>

**Comment by slmoebius** [comment]
And this happens with the latest version of odoo? I'm developing against a linux build from early January if I remember right and I could't reproduce the error.

**Comment by sramamkrishnan** [comment]
Yes i am using the latest version, Can you tell me the exact build that your using to develop this module?

**Comment by sramamkrishnan** [comment]
jan build fixed the issue for now.

**Comment by slmoebius** [comment]
After some hours of debugging we found the mysterious error. It turns out that the following code raises the error:
name = fields.Char(store=False)
But more mysterious is the solution for it:
name = fields.Char(store=False, search=True)
Could this be a bug in the Odoo orm?
