### ISSUE TITLE
Problems installing builder

### ISSUE THREAD

**Issue by DavidGoodenough** [slmoebius/builder#14]
I am trying to load builder into my test version of odoo 8, but I am having problems with the depenencies.

I have found generic_document_render, generic_document_render_jinja, and web_ace_editor on your github list, but I can not get them to show up in the list of available modules.

I have copied each directory into the addons directory, in exactly the same was that I did the builder directory, but nothing shows.

I notice that the installation section of the README.md is a TODO, any chance of putting some instructions in there?

**Comment by koubyak** [comment]
I'm also get an issue
Error details:
_description_searchable" while parsing /opt/odoo/.local/share/Odoo/addons/8.0/builder/views/res_config_model_view.xml:18, near

**Comment by akram1** [comment]
File "/media/akram/Data/projects/servers/Odoo/odoo8/openerp/models.py", line 1270, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
_description_searchable" while parsing /media/akram/Data/projects/servers/Odoo/addons/odoo8/builder/views/res_config_model_view.xml:18, near
<record model="ir.ui.view" id="builder_res_config_settings_form_view">
            <field name="name">builder.res.config.settings.form</field>
            <field name="model">builder.res.config.settings</field>
            <field name="arch" type="xml">
                <form string="Config View">
                    <sheet>
                        <div class="oe_right oe_button_box" name="buttons" invisible="not context.get('active_id', False)">

**Comment by bigdawgbz** [comment]
I got this error today while trying to install the builder.

Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/odoo-dev/odoo/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-dev/odoo/addons/web/controllers/main.py", line 941, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/odoo/odoo-dev/odoo/addons/web/controllers/main.py", line 929, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/addons/base/module/module.py", line 498, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/home/odoo/odoo-dev/odoo/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/odoo-dev/odoo/openerp/modules/loading.py", line 355, in load_modules
    loaded_modules, update_module)
  File "/home/odoo/odoo-dev/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo/odoo-dev/odoo/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/odoo/odoo-dev/odoo/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/odoo/odoo-dev/odoo/openerp/tools/convert.py", line 901, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/odoo/odoo-dev/odoo/openerp/tools/convert.py", line 987, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/odoo/odoo-dev/odoo/openerp/tools/convert.py", line 853, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/home/odoo/odoo-dev/odoo/openerp/tools/convert.py", line 763, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/addons/base/ir/ir_model.py", line 1077, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/addons/base/ir/ir_ui_view.py", line 264, in create
    context=context)
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 336, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/models.py", line 4074, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 462, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/models.py", line 4265, in _create
    recs._validate_fields(vals)
  File "/home/odoo/odoo-dev/odoo/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/odoo-dev/odoo/openerp/models.py", line 1270, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
_description_searchable" while parsing /home/odoo/odoo-dev/custom-addons/builder/views/res_config_model_view.xml:18, near
<record model="ir.ui.view" id="builder_res_config_settings_form_view">
            <field name="name">builder.res.config.settings.form</field>
            <field name="model">builder.res.config.settings</field>
            <field name="arch" type="xml">
                <form string="Config View">
                    <sheet>
                        <div class="oe_right oe_button_box" name="buttons" invisible="not context.get('active_id', False)">
                            <button class="oe_inline oe_stat_button" string="Fields" name="action_fields" type="object" icon="fa-list" context="{'default_model_id': id, 'default_module_id': module_id}"/>
                        </div>
                        <group>
                            <group>
                                <field name="module_id" invisible="1"/>
                                <field name="model"/>
                            </group>
                            <group>
                                <field name="name"/>
                            </group>
                        </group>
                        <notebook>
                            <page string="Fields">
                                <field name="field_ids">
                                    <tree string="Fields Description">
                                        <field name="position" widget="handle"/>
                                        <field name="name"/>
                                        <field name="setting_field_type"/>
                                        <field name="ttype"/>
                                    </tree>
                                    <form string="Field">
                                        <group>
                                            <group>
                                                <field name="setting_field_type"/>
                                                <field name="ttype" attrs="{'required': [('setting_field_type', '=', 'other')], 'invisible': [('setting_field_type', 'not in', ['other'])]}"/>
                                            </group>
                                            <group>
                                                <field name="name" attrs="{'required': [('setting_field_type', '=', 'other')], 'invisible': [('setting_field_type', 'not in', ['other'])], }"/>
                                                <field name="field_description"/>
                                            </group>
                                        </group>
                                        <notebook>
                                            <page string="Module" attrs="{'invisible': [('setting_field_type', 'not in', ['module'])]}">
                                                <group>
                                                    <group>
                                                        <field name="toggle_module_id"/>
                                                        <field name="toggle_module_name" attrs="{'required': [('setting_field_type', 'in', ['module'])]}"/>
                                                    </group>
                                                    <group>
                                                    </group>
                                                </group>
                                            </page>
                                            <page string="Groups" attrs="{'invisible': [('setting_field_type', 'not in', ['group'])]}">
                                                <field name="group_ids" domain="[('module_id', '=', module_id)]" attrs="{'required': [('setting_field_type', 'in', ['group'])]}"/>
                                            </page>
                                            <page string="Implied Group" attrs="{'invisible': [('setting_field_type', 'not in', ['group'])]}">
                                                <group>
                                                    <group string="Implied Group">
                                                        <field name="group_type"/>
                                                        <field name="group_system_group_id" attrs="{'invisible': [('group_type', 'not in', 'system')]}"/>
                                                        <field name="group_group_id" attrs="{'invisible': [('group_type', 'not in', 'module')]}"/>
                                                        <field name="group_name" attrs="{'required': [('setting_field_type', 'in', ['group'])]}"/>
                                                    </group>
                                                    <group/>
                                                </group>
                                            </page>
                                            <page string="Default" attrs="{'invisible': [('setting_field_type', 'not in', ['default'])]}">
                                                <group>
                                                    <group>
                                                        <field name="default_type"/>
                                                        <field name="default_system_model_id" attrs="{'invisible': [('default_type', 'not in', 'system')]}"/>
                                                        <field name="default_model_id" attrs="{'invisible': [('default_type', 'not in', 'module')]}"/>
                                                        <field name="default_model" attrs="{'required': [('setting_field_type', 'in', ['default'])]}"/>
                                                    </group>
                                                    <group>
                                                        <field name="default_system_model_field_id" attrs="{'invisible': [('default_type', 'not in', 'system')]}"/>
                                                        <field name="default_model_field_id" attrs="{'invisible': [('default_type', 'not in', 'module')]}"/>
                                                        <field name="default_field_name" attrs="{'required': [('setting_field_type', 'in', ['default'])]}"/>
                                                    </group>
                                                </group>
                                            </page>
                                            <page string="General" attrs="{'invisible': [('setting_field_type', 'not in', ['other'])]}">
                                                <group>
                                                    <group>
                                                        <field name="required"/>
                                                        <field name="readonly"/>
                                                        <field name="index"/>
                                                        <field name="select_level" attrs="{'readonly': [('ttype','in',['binary', 'serialized'])], 'invisible': [('ttype','in',['binary', 'serialized'])]}"/>
                                                        <field name="translate" attrs="{'readonly': [('ttype','not in',['char','html', 'text'])], 'invisible': [('ttype','not in',['char','html', 'text'])]}"/>
                                                    </group>
                                                    <group>
                                                        <field name="related"/>
                                                        <field name="size" attrs="{'readonly': [('ttype','not in',['char','reference'])], 'invisible': [('ttype','not in',['char','reference'])]}"/>

                                                        <label for="decimal_digits" attrs="{'invisible': [('ttype','not in',['float'])]}"/>
                                                        <div attrs="{'invisible': [('ttype','not in',['float'])]}">
                                                            <field name="decimal_digits" attrs="{'readonly': [('ttype','not in',['float'])]}" placeholder="Digits" class="oe_inline" style="width: 20%"/>
                                                            <field name="decimal_precision" attrs="{'readonly': [('ttype','not in',['float'])]}" placeholder="Precision" class="oe_inline" style="width: 20%"/>
                                                        </div>
                                                    </group>
                                                </group>
                                            </page>
                                            <page string="Relation" attrs="{'invisible': [('setting_field_type', 'not in', ['other']), ('ttype', 'not in', ['many2one','one2many','many2many'])]}">
                                                <group>
                                                    <group>
                                                        <field name="relation_model_id" attrs="{'required': [('ttype','in',['many2one','one2many','many2many'])],'readonly': [('ttype','!=','one2many'), ('ttype','!=','many2one'), ('ttype','!=','many2many')], 'invisible': [('ttype', 'not in', ['many2one','one2many','many2many'])]}"/>
                                                        <field name="relation" readonly="1" attrs="{'required': [('ttype','in',['many2one','one2many','many2many'])], 'invisible': [('ttype', 'not in', ['many2one','one2many','many2many'])]}"/>
                                                        <field name="relation_field" attrs="{'required': [('ttype','=','one2many')], 'readonly': [('ttype','!=','one2many')], 'invisible': [('ttype', 'not in', ['one2many'])]}"/>

                                                        <field name="auto_join" attrs="{'readonly': [('ttype','!=','many2one')], 'invisible': [('ttype', 'not in', ['many2one'])]}"/>
                                                        <field name="delegate" attrs="{'readonly': [('ttype','!=','many2one')], 'invisible': [('ttype', 'not in', ['many2one'])]}"/>
                                                    </group>
                                                    <group>
                                                    </group>
                                                </group>
                                                <group>
                                                    <group>
                                                        <field name="domain" attrs="{'readonly': [('relation','=','')], 'invisible': [('ttype', 'not in', ['many2one','one2many','many2many'])]}"/>
                                                        <field name="on_delete" attrs="{'readonly': [('ttype','!=','many2one')], 'invisible': [('ttype', 'not in', ['many2one'])]}"/>
                                                    </group>
                                                    <group>

                                                    </group>
                                                </group>
                                            </page>
                                            
                                            
                                        </notebook>
                                    </form>
                                </field>
                            </page>
                        </notebook>
                    </sheet>
                </form>
            </field>
        </record>

**Comment by onemoverx** [comment]
This might be due to a bug or weird setting with non stored fields, we'll check that out.

**Comment by bigdawgbz** [comment]
Okay...
