### ISSUE TITLE
How to install module builder in Ubuntu?

### ISSUE THREAD

**Issue by vishalkb2** [slmoebius/builder#15]
I don't know about how to install this module builder so any one help please.

**Comment by akram1** [comment]
1- download the module and its dependencies
   generic_document_render
   generic_document_render_jinja
   web_ace_editor
   report_extended
2- Put all modules in Odoo addons
3- Restart Odoo
4- Install the module

**Comment by akram1** [comment]
After a major rework on the module: the dependency modules changed. No need to install any third party ones. However, the new version gives me an error when installing.

https://github.com/slmoebius/builder/issues/14
