### ISSUE TITLE
Why do I need to be administrator in order to see/use Builder?

### ISSUE THREAD

**Issue by DavidGoodenough** [slmoebius/builder#16]
Having spent a considerable amount of time trying to find why I could not find evidence of Builder having installed Builder from my ID on my test Odoo system, and eventually looking in the view/menu.xml file and noticing that the parent item is base.menu_administration I tried logging on as admin, and low and behold the Settings menu item Builder and its children appeared.

It would be useful if it is required that you are administrator in order to use Builder that it said this somewhere.

Secondly while I know that creating new databases requires you to be administrator, just about everything else is controlled by an access setting, which I think translates as membership of a group.  Could there not be a Designer group?

**Comment by onemoverx** [comment]
thanks for the feedback @DavidGoodenough,  this is something that we need to address yet, along with showing only the modules created by the user etc. noted for next update.

**Comment by onemoverx** [comment]
@DavidGoodenough  moved to top level menu "Module Builder" and set the permissions so all users can use it
