### ISSUE TITLE
When I create a model and try to save it, it complains that field "module" is invalid

### ISSUE THREAD

**Issue by DavidGoodenough** [slmoebius/builder#17]
but I can not find any highlighted field, or any field in any of the tabs on the module dialog called module.  

How do I create a module?

**Comment by onemoverx** [comment]
not sure what you mean by that, can you upload a image to see what you're doing? 
you fill the basic module info when creating a new module, save it, start creating or importing models in the model tab, go to view tab and create from new model view ....

**Comment by DavidGoodenough** [comment]
If I create a new module, give it a name and press Save I get the error described in issue #13.

I am running with the latest overnight odoo deb, and I have git pulled builder to make sure I am up to date.

I assumed that this error meant that it needed some content in the module somewhere, before I tried saving the module I tried creating a model, and it was when I tried to save it that I got the popup saying that the required module field was missing.
