### ISSUE TITLE
inherited model and view definition

### ISSUE THREAD

**Issue by DobiSoft** [slmoebius/builder#3]
Hi,

I start to check the features of this great addon. 
1. I inherited the product.template model and add a single char field to it. The generated model.py was good 
2. Tried to inherit the already defined view the "product_template_form_view". But i cannot figure how to fill the inherited field view id to position my new field. I tried do set up an xpath but failed too.
The generated xml was not correct, the inherited view was not setup.

Is that feature is WIP and not complete or how can I setup such a inherited view?

Regards

**Comment by yunier-rojas** [comment]
In the test I did, the generated view didn't set the field "inherit_id". In the other hand, if you want to include field inside the xpath you just need to add them in the page "Fields"

**Comment by onemoverx** [comment]
Indeed, this is a known bug given that right now views cannot render the complete record but only the arch field.
