### ISSUE TITLE
Incorrect import of a module

### ISSUE THREAD

**Issue by akram1** [slmoebius/builder#5]
I imported a basic module I made that has these declarations:
3 view items (form,tree,search)
1 Menu item
1 Action Window Item
1 ACL file
1 Record Rule
2 Buttons in Form View
10 Files 2__init__.py,__openerp.py, models.py, 4 xml, 1 csv, icon.png

The result of the import is
6 views (1 duplicate of each view, if you hit configure view, there are no fields in the field list)
1 Menu Item
0 Action item
0 ACL declaration
0 Record Rule
0 Button
0 module files imported

The result of export (import then export)
6 views (1 duplicate of each view)
1 Menu Item (without action attribute)
0 Action item
0 ACL declaration
0 Record Rule
4 Button (2 buttons in each Form View)
8 Files 2__init__.py,__openerp.py, models.py, 3 xml, icon.png

Here is the main list of the module code. It is working module with no errors.
**__openerp__.py
    "name" : "todo_app",
    "version" : "0.1",
    "category" : "Uncategorized",
    "licence" : "AGPL-3",
    "description": """
To Do Application
====================================
Task managment
                    """,
    "depends" : ['mail'],
    "data" : [
                'views/views.xml',
                'views/actions.xml',
                'views/menu.xml',
				'security/ir.model.access.csv',
				'security/access_rules.xml',
                ],
    "demo" : [],
    "installable": True,
    "auto_install": False,
    "application": True,
}

**models.py
from openerp import models, fields, api, tools, _

class TodoTask(models.Model):
	_name = 'todo.task'
	_description = 'todo.task'

	name = fields.Char( required=True, string='Name',)
	is_done = fields.Boolean( string='Done?',)
	active = fields.Boolean( string='Active?',default='True',)

	@api.one
	def	do_toggle_done(self):
		self.is_done = not self.is_done
		return True

	@api.multi
	def	do_clear_done(self):
		done_recs = self.search([('is_done', '=', True)])
		done_recs.write({'active': False})
		return True

**view xml files
		<menuitem id="menu_todo_task"
			name="Tasks"
			parent="mail.mail_feeds"
			sequence="20"
			action="action_todo_task"	
		/>        

		<act_window	id="action_todo_task"
			name="Task"
			res_model="todo.task"
			view_mode="tree,form"	
		/>
		<record	id="view_form_todo_task" model="ir.ui.view">
			<field name="name">Task Form</field>
			<field name="model">todo.task</field>
			<field name="arch" type="xml">
				<form>
					<header>
					
						<button	name="do_toggle_done" type="object" string="Toggle Done" class="oe_highlight" /> 
						<button	name="do_clear_done" type="object" string="Clear All Done" />
					</header>
					<sheet>
						
						<group name="group_top">
							<group name="group_left">
								<field name="name"/>
							</group>
							<group name="group_right">
								<field name="is_done"/>
								<field name="active" readonly="1"/>
							</group>
						</group>
					</sheet>
				</form>
			</field>
		</record>
		<record	id="view_tree_todo_task" model="ir.ui.view">
			<field name="name">Task List</field>
			<field name="model">todo.task</field>
			<field name="arch" type="xml">
				<tree colors="gray:is_done==True">
					<field name="name"/>
					<field name="is_done"/>
				</tree>
			</field>
		</record>
		<record	id="view_filter_todo_task" model="ir.ui.view">
			<field name="name">Task Filter</field>
			<field name="model">todo.task</field>
			<field name="arch" type="xml">
				<search>
					<field name="name"/>
					<filter string="Not	Done" domain="[('is_done','=',False)]"/>
					<filter string="Done" domain="[('is_done','!=',False)]"/>
				</search>
			</field>
		</record>

**access rule xml
	<data noupdate="1">
		<record	id="todo_task_user_rule" model="ir.rule">
			<field	name="name">ToDo Tasks only	for	owner</field>
			<field	name="model_id"	ref="model_todo_task"/>
			<field	name="domain_force">[('create_uid','=',user.id)]</field>
			<field	name="groups" eval="[(4,ref('base.group_user'))]"/>
		</record>
	</data>

**ACL csv file
id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink
access_todo_task_group_user,todo.task.user,model_todo_task,base.group_user,1,1,1,1

**Comment by onemoverx** [comment]
well the import module feature doesn't work (or ever will) work as you (we) could expect, and is not a feature to rely on, instead use it for explore module structure only (mainly models and fields), in fact is quite possible to remove it from the builder and add it as an independent module.
